### ISSUE TITLE
KeyError: 'outline' when using the Text tool.

### ISSUE THREAD

**Issue by PJ-Singh-001** [maoschanz/drawing#521]
## Description

I see this error in the console when running Drawing from the command line. I clicked the text toolbar icon when this error appeared.

    GDK_BACKEND=x11 drawing
    Traceback (most recent call last):
      File "/usr/share/drawing/drawing/window.py", line 208, in _update_active_tool_from_flowbox_signal
        self.switch_to(selected_tool.id)
      File "/usr/share/drawing/drawing/window.py", line 918, in switch_to
        self.set_window_subtitles()
      File "/usr/share/drawing/drawing/window.py", line 652, in set_window_subtitles
        subtitles_list = self.active_tool().get_editing_tips()
      File "/usr/share/drawing/drawing/tool_text.py", line 94, in get_editing_tips
        bg_label = {
    KeyError: 'outline'

### Steps to reproduce the bug

1. Install Drawing in Ubuntu 22.04 from the PPA.
2. Launch using `GDK_BACKEND=x11 drawing`. (`GDK_BACKEND` is necessary because I am running Nvidia with Wayland).
3. Notice the above error in the console.

## System

- Device: Laptop
- OS: Ubuntu 22.04
- Desktop environment: GNOME Shell, Wayland Session + NVIDIA
- Package format: PPA (ppa:cartes/drawing)
- App version: Drawing 1.0.1

**Comment by maoschanz** [comment]
thanks for the report
