### ISSUE TITLE
1.0.1: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [maoschanz/drawing#547]
## Description
Looks like test suite is failing

## System

- Device (desktop computer/tablet/phone/...): N/A
- OS: Linux x86/64
- Desktop environment: N/A
- Package format: N/A
- App version: N/A

Here is test suite output
```console
+ cd drawing-1.0.1
+ /usr/bin/meson test -C noarch-redhat-linux-gnu --num-processes 48 --print-errorlogs
ninja: Entering directory `/home/tkloczko/rpmbuild/BUILD/drawing-1.0.1/noarch-redhat-linux-gnu'
ninja: no work to do.
1/3 Validate desktop file          OK              0.02s
2/3 Validate schema file           OK              0.01s
3/3 Validate appstream file        FAIL            0.20s   killed by signal 11 SIGSEGV
>>> MALLOC_PERTURB_=120 /usr/bin/appstream-util validate data/com.github.maoschanz.drawing.appdata.xml
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
stdout:
data/com.github.maoschanz.drawing.appdata.xml:
stderr:

(appstream-util:653222): GLib-GIO-CRITICAL **: 14:41:25.234: g_proxy_resolver_lookup: assertion 'G_IS_PROXY_RESOLVER (resolver)' failed
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――


Summary of Failures:

3/3 Validate appstream file FAIL            0.20s   killed by signal 11 SIGSEGV

Ok:                 2
Expected Fail:      0
Fail:               1
Unexpected Pass:    0
Skipped:            0
Timeout:            0

Full log written to /home/tkloczko/rpmbuild/BUILD/drawing-1.0.1/noarch-redhat-linux-gnu/meson-logs/testlog.txt
error: Bad exit status from /var/tmp/rpm-tmp.seJLci (%check)


RPM build errors:
    Downloading https://github.com/maoschanz/drawing//archive/1.0.1/drawing-1.0.1.tar.gz to /home/tkloczko/rpmbuild/SOURCES/drawing-1.0.1.tar.gz
```

**Comment by maoschanz** [comment]
sorry, i usually don't run those tests at all, i trust gnome builder to check that for me

do you know what's the version of meson?

(my employer's computer has 0.61.2 and it fails with a completely different error...) 

```
user@dell-3431:~/drawing/_build$ meson test
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 146, in run
    return options.run_func(options)
  File "/usr/lib/python3/dist-packages/mesonbuild/mtest.py", line 2005, in run
    setup_vsenv(b.need_vsenv)
AttributeError: 'Build' object has no attribute 'need_vsenv'

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**Comment by maoschanz** [comment]
```
user@dell-3431:~/drawing$ appstream-util validate _build/data/com.github.maoschanz.drawing.appdata.xml 
_build/data/com.github.maoschanz.drawing.appdata.xml: OK
```

idk what the gio proxy resolver is supposed to do but it's out of my control 🤷‍♂️  my version of appstream-util is 0.7.18 if it helps
